### ISSUE TITLE
How in development is in development for this package?

### ISSUE THREAD

**Issue by ragingdave** [spatie/laravel-settings#1]
I came across this out of a need to have a good way to handle app wide configurations that are cached but DB-persisted and this seems to fit the bill almost perfectly at least from a quick overview.

So that's basically my question is how unstable is this package for potential use?

**Comment by rubenvanassche** [comment]
Hi @ragingdave,

I hope this will be a really good fit for your application, we've being using it internally for quite a while and really love it! You could already use it I'll guess. The api won't change that much anymore till we release v1.0 . And at the moment it should work as expected. But, I'm still fiddling a lot with the internal structures and there's not a lot of documentation available. 

I'm hoping to release a first stable version of this package within a month or so. You can use it already. But I wouldn't recommend deploying it to production (yet).
