### ISSUE TITLE
Class 'Spatie\LaravelSettings\SettingsMigration' not found

### ISSUE THREAD

**Issue by thomas-j92** [spatie/laravel-settings#10]
My Migration file (same as your example): 

`use Spatie\LaravelSettings\SettingsMigration;

class CreateGeneralSettings extends SettingsMigration
{
    public function up(): void
    {
        $this->migrator->add('general.site_name', 'Spatie');
        $this->migrator->add('general.site_active', true);
    }
}`

When I proceed to run 'php artisan migrate' I get the following error:

`Class 'Spatie\LaravelSettings\SettingsMigration' not found`

Any ideas what I'm doing wrong?

Cheers

**Comment by ragingdave** [comment]
It might just be simply that you have the wrong FQCN, which should actually be `Spatie\LaravelSettings\Migrations\ SettingsMigration`. This looks like the docs are just wrong for this specific example.

**Comment by rubenvanassche** [comment]
That's correct, @alexjustesen added a PR that solves this: https://github.com/spatie/laravel-settings/pull/9.
