### ISSUE TITLE
Trouble to understand how to update settings

### ISSUE THREAD

**Issue by Drillan767** [spatie/laravel-settings#11]
Hello,

I've just installed  this library in my project, I want to use it to store details such as social networks, but also pieces of configuration such as "should we allow users to register on the website?"

However, when I read the documentation, it looks like I need to "hardcode" my settings, then migrate them. I'm pretty sure I'm missing something. Is it possible to edit the settings from a form in my website, and if so, how should I proceed?

**Comment by rubenvanassche** [comment]
Hi @Drillan767,

It is indeed true you have to hardcode your settings like a boolean for: "should we allow users to register on the website?". Migrating will add these settings (and in this case the boolean) to the database/redis. You can now inject your settings class everywhere in Laravel and it will have a value for the boolean. 

When you want to update the value of this boolean then you should update the value of the boolean in the settings class and call the `save` method on it. The package will update the database/redis then with the new value of the boolean.

Does that make sense?

**Comment by Drillan767** [comment]
Hello again, thank you for the explaination, I realized I overlooked the "update" part, and it (of course) works as a charm. Thanks again!
