### ISSUE TITLE
__debugInfo should not throw exception

### ISSUE THREAD

**Issue by netpok** [spatie/laravel-settings#116]
Throwing an exception from the `__debugInfo` magic method in the `Settings` class will result in an ErrorException with `__debuginfo() must return an array`.

This is a problem in our configuration where we use this package and the multitenancy package. Under php 7.4 everythimg worked but running the `ide-helper:meta` command breaks under php8.1.

---

Also I don't really understand the reason for the `__debugInfo` method, first I thought it's there so values are loaded for a `var_dump` call but returning null defeats that purpose.

**Comment by rubenvanassche** [comment]
`__debugInfo` will indeed load values from the repository when `var_dump` was called, though I probably forget to return values. Fixed this in v2.3.3!
