### ISSUE TITLE
Lumen Framework

### ISSUE THREAD

**Issue by suabahasa** [spatie/laravel-settings#12]
Can you make it compatible with Lumen framework?

thank you

**Comment by rubenvanassche** [comment]
Hi @suabahasa,

We're not using Lumen at the moment, so I'm not sure what needs to happen to make this work in Lumen. But I would accept a fully tested PR that supports Lumen.

**Comment by suabahasa** [comment]
I'm didn't know how to make test, but it now run on my lumen project.

the change I made is

- using `Laravel\Lumen\Application` instead `Illuminate\Foundation\Application`.
- using `app()` instead `resolve()`

**Comment by rubenvanassche** [comment]
Is there a way for LUMEN

**Comment by suabahasa** [comment]
how about using Union type in SettingContainer's property and method parameter instead `use`

I will try to PR my fork's commit

**Comment by rubenvanassche** [comment]
Looking forward to your PR!
