### ISSUE TITLE
Use full import for Cache Facade instead of alias

### ISSUE THREAD

**Issue by IAmRGroot** [spatie/laravel-settings#130]
Is there a specific reason to use the alias in stead of the full Facade import for the caching?

I came across a project that doesn't have the Alias in config/app.php and laravel-settings crashes because it uses the alias. My suggestion would be to use the full path:

Now:
```php
use Cache;
```

Full import:
```php
use Illuminate\Support\Facades\Cache;
```

**Comment by rubenvanassche** [comment]
Not a reason, I would merge such a PR!
