### ISSUE TITLE
Settings without Default Values

### ISSUE THREAD

**Issue by mprythero** [spatie/laravel-settings#135]
Is there a way around the requirement for default values to leave some null? There are some settings fields that aren't filled out, and I would like the option of not having to have a default value for everything when some are not required.

**Comment by gavinhewitt** [comment]
I came here for the same thing :-)

**Comment by gavinhewitt** [comment]
> Is there a way around the requirement for default values to leave some null? There are some settings fields that aren't filled out, and I would like the option of not having to have a default value for everything when some are not required.

Silly us. When you change `public string $something;` to `public ?string $something;` of course. Doh!
