### ISSUE TITLE
updated to php8 

### ISSUE THREAD

**Issue by TheFogOfWar1** [spatie/laravel-settings#15]
TypeError 

  Spatie\LaravelSettings\Support\DiscoverSettings::within(): Argument #1 ($directories) must be of type array, null given, called in /Users/wvdm/beyond-solutions/beyondselection/vendor/spatie/laravel-settings/src/SettingsContainer.php on line 49

  at vendor/spatie/laravel-settings/src/Support/DiscoverSettings.php:25
     21▕     {
     22▕         $this->basePath = app()->path();
     23▕     }
     24▕ 
  ➜  25▕     public function within(array $directories): self
     26▕     {
     27▕         $this->directories = $directories;
     28▕ 
     29▕         return $this;

**Comment by SomaiyaJinal** [comment]
@TheFogOfWar1  try with deleting all files from bootstrap/cache directory except .gitignore file.

**Comment by TheFogOfWar1** [comment]
Thanks, this did the job!
