### ISSUE TITLE
Caching Not working

### ISSUE THREAD

**Issue by bmtamim** [spatie/laravel-settings#153]
Hi there, I have used this package in my project, Now, I am very disappointed with this package,

You can see on the screenshot, It always does 2 queries in the database. 
https://prnt.sc/DAtAlfw_ju54

I am using it like this:
https://prnt.sc/XWGQykjl4iqK

It should be cached somewhere, because eI have used this
`SETTINGS_CACHE_ENABLED=true`

 I know that spatie is an outstanding company, so I used this.
 
 Thanks

**Comment by rubenvanassche** [comment]
We're all open source developers in here, we do this work in our spare time for the community. Creating an issue with this kind of attitude won't win you any favors of the people maintaining these kind of open source projects. 

If something is broken, then first try to find out why it is broken, then maybe send in a PR fixing the issue. If you can't find out what's exactly going on, then ask the open source maintainers for help. 

Complaining that you’re disappointed will certainly not motive us to help you.

For future readers, using the package correctly by reading the docs and using the container to resolve settings should fix the issue as stated in the docs.
