### ISSUE TITLE
Package spatie/data-transfer-object is abandoned, you should avoid using it. Use spatie/laravel-data instead.

### ISSUE THREAD

**Issue by lucianobosco** [spatie/laravel-settings#162]
`"spatie/laravel-settings": "^2.4"`

When running `composer update` I'm getting this warning
`Package spatie/data-transfer-object is abandoned, you should avoid using it. Use spatie/laravel-data instead.`

As far I see, `spatie/data-transfer-object` is included in composer.json file

```
"require": {
        "php": "^7.4|^8.0",
        "ext-json": "*",
        "illuminate/database": "^8.73|^9.0",
        "doctrine/dbal": "^2.13|^3.2",
        "phpdocumentor/type-resolver": "^1.5",
        "spatie/data-transfer-object": "^2.8|^3.7",
        "spatie/temporary-directory": "^1.3|^2.0"
    },
```
Edit: I've just found this pending PR https://github.com/spatie/laravel-settings/pull/161

**Comment by hamzaelmaghari** [comment]
Hope it get fix soon, cause spatie is decided to stop maintaining that package.
