### ISSUE TITLE
Caching and multi-tenancy (multi database)

### ISSUE THREAD

**Issue by Allgoodnamesargone** [spatie/laravel-settings#166]
Hello,
I have a multi-tenancy project and there's a setting that is made/modified centrally but i need to get it's values within tenant. This is fine, i have made a new repository named `database-central` and used `repository` function within the settings class to return it.

BUT, while enabling the cache and using redis, it creates caches with tenant's prefix! this is the correct behavior for non-central settings, in my use case it breaks things because it gets the cached value even thought i have updated/edited the settings value.

This is a bug rather than a feature request because changing repositories doesn't makes much sense while the cache is one for all.

The fix that i can think of is a breaking change, it is removing the `settings.cache` config and making the package to use `settings.repositories.$NAME.cache` as for the cache settings.

The only workaround for this to work is disabling cache, which is fine only for development environment.

**Comment by atapatel** [comment]
@Allgoodnamesargone which version of laravel-settings you are using?

**Comment by rubenvanassche** [comment]
This should be fixed with the next version.

**Comment by joelharkes** [comment]
Is there a way to make the settings multitenant based on a database model eg: Users or Clients?
