### ISSUE TITLE
 Typed property App\Settings\GeneralSettings::$name must not be accessed       before initialization                                                     

### ISSUE THREAD

**Issue by devscript-abdo** [spatie/laravel-settings#18]
Typed property App\Settings\GeneralSettings::$name must not be accessed       before initialization    

I got this problem when I use this settings Class  in some different namespace

**Comment by amrography** [comment]
Make sure you have `$name` property as public with your desired type in target setting class

```php
namespace App\Settings;

use Spatie\LaravelSettings\Settings;

class GeneralSettings extends Settings
{
    public string $name; // <-- You need to have this line

    public static function group(): string
    {
        return 'general';
    }
}
```

**Comment by rubenvanassche** [comment]
@devscript-abdo, did @amrography solution solve the problem? If not, make sure you've migrated each property within your settings class.

**Comment by devscript-abdo** [comment]
@rubenvanassche problem solved by define a default value for the $name : 
public $name = 'xyz';

**Comment by amrshakya** [comment]
@devscript-abdo @rubenvanassche I'm having the same issue getting 

``Typed property App\Settings\AdminSetting::$expired_payin_limit_notify must not be accessed before initialization``

```
<?php

namespace App\Settings;

use Spatie\LaravelSettings\Settings;

class AdminSetting extends Settings
{
    public array $white_lists;

    public int $expired_payin_limit_notify;   //  <---  this has been defined
    public static function group(): string
    {
        return 'admin';
    }
}

```

**Comment by rubenvanassche** [comment]
There must be something wrong with mapping the properties from your database onto your settings class. Could you please check for typo's. We do unregister all public properties when the class is constructed so they can be loaded when required. That's why the exception says that the property is not initialized.

**Comment by amrshakya** [comment]
@rubenvanassche After i re-updated the value for the setting it issue seems to be fixed. Thanks.

**Comment by marcuschristiansen** [comment]
Make sure, if your settings are cached, you clear your cache. 

`php artisan settings:clear-cache`

**Comment by amashkarin** [comment]
I had same issue on production environment after release new setting. Reason is default config:
```
    'cache' => [
        'enabled' => env('SETTINGS_CACHE_ENABLED', env('APP_ENV', 'production') === 'production'),
        'store' => 'redis',
        'prefix' => null,
        'ttl' => null,
    ],
```
don`t forget clear cache after updating
