### ISSUE TITLE
Boolean always returns false

### ISSUE THREAD

**Issue by bistory** [spatie/laravel-settings#183]
Hi,

First, thanks for your packages, they are really great !

I started to test laravel-settings but found a bug. I have set a boolean setting like in the example, however, it always returns false...

I just created some test settings, a migration, enabled cache (file in local) and showed them with dd, here is what I have in DB : 

<img width="781" alt="Capture d’écran 2022-12-20 à 15 57 19" src="https://user-images.githubusercontent.com/108102/208699325-c4fa1057-0433-460b-8342-757feabfc477.png">

And here is what I get with dd()

<img width="617" alt="Capture d’écran 2022-12-20 à 15 57 37" src="https://user-images.githubusercontent.com/108102/208699352-cad81e63-358e-4618-8389-ebc3196cc627.png">

Are you able to reproduce this bug ?

Thanks 🥇

**Comment by rubenvanassche** [comment]
Are you using caching?

**Comment by bistory** [comment]
Yes I am, this issue only happens when cache (file driver) is enabled

**Comment by rubenvanassche** [comment]
Hmmm looks like your cache isn't cleared correctly. Caches are updated when you update a settings class and cleared when running `php artisan settings:clear-cache`. Does that last command fix the issue? 

If not, could you reproduce this in a fresh application and send the repo to me.

**Comment by bistory** [comment]
Thanks a lot for your reply, however I will close this issue as I was told this week the project I was working on is abandonned... So I had to move on...

**Comment by rubenvanassche** [comment]
Oh that's sad to hear, good luck!

**Comment by bistory** [comment]
> Oh that's sad to hear, good luck!

Thanks :-)
