### ISSUE TITLE
New entries instead of update

### ISSUE THREAD

**Issue by mohamedsabil83** [spatie/laravel-settings#227]
Beginning from v3.0, when updating any setting, it adds a new record(s) instead of updating the current ones. I had to return to v2.8.3 which works as expected.

**Comment by mohamedsabil83** [comment]
After more digging, I found it just needs to update the settings table like mentioned in the [UPGRADING](https://github.com/spatie/laravel-settings/blob/main/UPGRADING.md)

**Comment by bekbolot1407** [comment]
@mohamedsabil83   
Please tell me how you fixed this exactly? After all, I did the same thing, and I write new data instead of updating old data. I will be glad to see your answer

**Comment by bekbolot1407** [comment]
@mohamedsabil83 
Please tell me how you fixed this exactly? After all, I did the same thing, and I write new data instead of updating old data. I will be glad to see your answer

**Comment by mohamedsabil83** [comment]
Sure @bekbolot1407. Just create a migration. Copy the content from [UPGRADING](https://github.com/spatie/laravel-settings/blob/main/UPGRADING.md). Then, run it.
