### ISSUE TITLE
Accesing GeneralSettings in Controllers

### ISSUE THREAD

**Issue by dapehe94** [spatie/laravel-settings#230]
### Discussed in https://github.com/spatie/laravel-settings/discussions/229

<div type='discussions-op-text'>

<sup>Originally posted by **dapehe94** July  6, 2023</sup>
Hi all

To access GeneralSettings in the controller is it necessary to include this in Controller?

`use App\Models\Settings\GeneralSettings;`

If I don't add it, it doesn't work :-(

My configuration in config\settings.php

```
 'settings' => [
        GeneralSettings::class,
        CoinsSettings::class
    ],
....
'setting_class_path' => app_path('Models/Settings'),
...
    'auto_discover_settings' => [
        app_path('Models/Settings'),
    ],
```</div>

**Comment by MusheAbdulHakim** [comment]
If you want to access the class without including it in the controller, you could use the **app()** method to get the class instance. Like this:

```
app(App\Models\Settings\GeneralSettings)->proper;
```

**Comment by rubenvanassche** [comment]
Please don't create issues when you've already created a discussion.
