### ISSUE TITLE
calling migrator's update method throws an error

### ISSUE THREAD

**Issue by chosww** [spatie/laravel-settings#245]
When I use migrator's update method, I get an error saying that "Class "GeneralSettings" not found" from `vendor/spatie/laravel-settings/src/Migrations/SettingsMigrator.php:188`. The error message suggest importing the GeneralSettings class: "A class import is missing: You have a missing class import. Try importing this class: `App\Settings\GeneralSettings`".

**Comment by rubenvanassche** [comment]
Try clearing your caches also the specific settings caches.

I'm gonna close this one since this does't seem like a problem with the package, if you think this is the case, feel free to comment.
