### ISSUE TITLE
Support for Doctrine DBAL 3

### ISSUE THREAD

**Issue by Sn0wCrack** [spatie/laravel-settings#25]
Currently Laravel and various Laravel adjacent packages (such as laravel-ide-helper) have locked their doctrine/dbal dependency at: "^2.6|^3" meaning version 3 is selected when using PHP 8.

Could the dependency on this package be changed to match that of Laravel, or at least made to include version 3 for usage within PHP 8?

**Comment by rubenvanassche** [comment]
This should be fixed in v1.0.5
