### ISSUE TITLE
Cannot Save An Array of user ID's to the payload.

### ISSUE THREAD

**Issue by FireOpsPhil** [spatie/laravel-settings#265]
I have Laravel-Settings working for a variety of data types, minus arrays.  This past week, I tried to add an ARRAY of user ids for the first time.  The data is coming to the controller, already formatted as a Json string.  If I do a die-dump on the incoming data, it confirms the Json string as follows:
```
array:2 [
0 => "1"
1 => "2"
]
```
In my settings, I have the following:
```
 public array $notifyUsers; 
```
In my controller, I am trying to set the value for that setting as follows:
```
$injurySettings->notifyUsers = $validatedData['notifyUsers'];
```
This causes the following error:
```
Cannot assign **string** to property App\Settings\InjuryModuleSettings::$notifyUsers of type **array**
```
If I change my setting to the following
```
 public string $notifyUsers; 
```
I get the exact opposite error, as if to confirm it is an array:
```
Cannot assign **array** to property App\Settings\InjuryModuleSettings::$notifyUsers of type **string**
```

Is this a bug, or am I missing something?

**Comment by rubenvanassche** [comment]
Please, use the issue format we provide and create a new one with a test.

**Comment by tfevan** [comment]
I answered this question [here](https://github.com/spatie/laravel-settings/discussions/267#discussioncomment-11210461).
