### ISSUE TITLE
Setting Upsert only insert and doesnt update

### ISSUE THREAD

**Issue by chimuel-jlc** [spatie/laravel-settings#275]
Laravel 11 bug caused by upsert to only insert and not update settings on line #76 on file [/src/SettingsRepositories/DatabaseSettingsRepository.php](https://github.com/spatie/laravel-settings/blob/main/src/SettingsRepositories/DatabaseSettingsRepository.php#L76)

Propose fixed:
```php
public function updatePropertiesPayload(string $group, array $properties): void
{
    $model = $this->getBuilder();
    $propertiesInBatch = collect($properties)->map(function ($payload, $name) use ($group, $model) {
        $model->updateOrCreate(
            [
                 'group' => $group,
                 'name' => $name,
            ],
            [
                'group' => $group,
                'name' => $name,
                'payload' => $encoder($payload),
            ]
        );
    });
}
```

**Comment by rubenvanassche** [comment]
As far as I'm aware all our tests are running fine even on Laravel 11? Could you be more specific what's exactly broken? Gonna close this for now but feel free to answer and I'll take a further look.
