### ISSUE TITLE
Settings looks for database, even before created

### ISSUE THREAD

**Issue by bhattji** [spatie/laravel-settings#284]
**✏️ Describe the bug**

I am facing a weird issue with Filament Settings Plugin (Spatie Settings)

I have installed it and it works fine, however, if delete the database and try "php artisan migrate" it doesn't work. It asks for the settings table (created for Settings Plugin) with all the settings values. Fortunately, I did have the settings.sql saved. but if not, then how would I create the database?

**↪️ To Reproduce**

Delete the database (or give a new database name in .env file) and try "php artisan migrate"

**Comment by rubenvanassche** [comment]
Could you please provide a demo project showing this bug?

**Comment by As3ad10** [comment]
@bhattji 

Yes, I'm also having the same issue, 

> Could you please provide a demo project showing this bug?

just create a new db as he said, then you will have an error:
```
Tried loading settings 'App\Settings\GeneralSettings', and following properties were missing: company_name, company_address, company_logo
```

this error appears in console when running `php artisan anything ` and in the browser

the solution worked for me is to comment every route that has a setting passed as variable temporary, then I can run migrate

**Comment by bhattji** [comment]
The solution is check Schema::hasTable('settings') before accessing setting, however that doesn't work if the DB is not created already

**Comment by rubenvanassche** [comment]
I'm not able to reproduce this, since you're mentioning the filament plugin, please open an issue over there.
