### ISSUE TITLE
Prevent error argument type when package:discover is running

### ISSUE THREAD

**Issue by Atiladanvi** [spatie/laravel-settings#3]
When the php artisan package:discover --ansi is running i get this error
 ``` 
> @php artisan package:discover --ansi

   TypeError 

  Argument 1 passed to Spatie\LaravelSettings\Support\DiscoverSettings::within() must be of the type array, null given, called in /home/danvi/Projects/sistema_janelaunica/vendor/spatie/laravel-settings/src/SettingsContainer.php on line 49
```
Steps to reproduce:
1 - Remove vendor path and cache files of laravel
2 - Run composer install

**Comment by rubenvanassche** [comment]
@Atiladanvi seems that the config value of `settings.auto_discover_settings` is `null`, it should be an `array`. Could you check why this config value was not set? 

Did a clean install and the problem doesn't pop up so, I'll guess there's something wrong with your config file.

**Comment by Atiladanvi** [comment]
I'm sorry for this issue. I don't know what has happened but now (today :neckbeard: ) it work. Thanks for your reply !

**Comment by juliomotol** [comment]
I've recently encountered this problem. I ran `php artisan config:clear` and it worked. It must've had something to do with the cached config.
