### ISSUE TITLE
Lumen 8 Call to undefined function Spatie\LaravelSettings\resolve() 

### ISSUE THREAD

**Issue by oulfr** [spatie/laravel-settings#31]
in lumen8 i have this error:

Call to undefined function Spatie\LaravelSettings\resolve() 

this is a fix:

https://github.com/spatie/laravel-permission/commit/cbdca3c1be8461fa6f411dca68638c452b1062ba

**Comment by oulfr** [comment]
any update to this ?

**Comment by rubenvanassche** [comment]
There's an open PR for this, but it should be rebased on the most recent version of master:

https://github.com/spatie/laravel-settings/pull/29

**Comment by oulfr** [comment]
can you accept the change i have just made the pull request for this

**Comment by rubenvanassche** [comment]
Could you check v2, this has no resolve calls anymore in the app code

**Comment by oulfr** [comment]
you still use Illuminate\Foundation\Application in your SettingsContainer this class it doesn't exist in lumen, so it will not be compatible with lumen

**Comment by rubenvanassche** [comment]
This class is removed in v2.0.1 and replaced by `Illuminate\Container\Container` which should be available both in Laravel and Lumen
