### ISSUE TITLE
Property without type, only in docblock

### ISSUE THREAD

**Issue by azzumed** [spatie/laravel-settings#32]
The example not works
https://github.com/spatie/laravel-settings#user-content-local-casts-1:~:text=%2F%2F%20By%20the%20docblock%20of%20a%20property

![image](https://user-images.githubusercontent.com/76779534/109402080-ea074400-7963-11eb-9c52-b9ecb98830e3.png)
![image](https://user-images.githubusercontent.com/76779534/109402083-f4c1d900-7963-11eb-852b-e4c9c63f8892.png)

Getting error when calling `app(CastSettings::class)`
![image](https://user-images.githubusercontent.com/76779534/109402207-f0e28680-7964-11eb-8d48-723698ceefc3.png)

**Comment by rubenvanassche** [comment]
Hi @azzumed version 1.0.8 fixes this issue
