### ISSUE TITLE
The way to implements settings for the each users

### ISSUE THREAD

**Issue by Atiladanvi** [spatie/laravel-settings#5]
I wanted to ask if I can write Settings Repository thinking to filter groups by specific user without broken something ? Where the points of change to do this ?  I want to add the colluns: user_id or target_type and target_id. What do you think about this.

**Comment by rubenvanassche** [comment]
Hi @Atiladanvi,

I'm not entirely understanding your question. Do you want to create a settings group for each user with some properties in it? The package wasn't exactly created for that although you could try to overwrite the `group` function somewhere so it returns something like `user.{user_id}` for each user. Not really sure if that's possible but that's the first thing I would check out.

Good luck!

**Comment by Atiladanvi** [comment]
All rigth !. I will try do something like this.

**Comment by KolyaSirik** [comment]
@Atiladanvi, I have same question

Have you found solution for this?

**Comment by Atiladanvi** [comment]
@KolyaSirik,  I was add a setting collun in my users table and casting to  array. I can do something like this:
```php
$data['settings'] = [
  'last_profile_active_id' => $role->id
];

$user = User::create($data);

$user->settings['last_profile_active_id']  = 2;

$user->save();
```
Look at documentation: https://laravel.com/docs/8.x/eloquent-mutators#array-and-json-casting

I was chekeed the posiibilities to change the behaviour of this package but i think it's not possible becouse that architeture is made to work only with general settings. I tried implements the repository interface but has many points of change to do this. Is not viable for me. If you wanna keep user setings, the way more simple to do this is add json collun with array cast in eloquent model. By the way , i will write a simple class to handler that variables and simplify the uses: Design: 
`$user->setSetting('key', $var), $user->getSetting('key', $var), $user->settings`

**Comment by frknasir** [comment]
I guess this package is not suitable for a multi tenant app

**Comment by atapatel** [comment]
@frknasir Did you have any solution/patch in mind to make this package available for tenant base application.

**Comment by frknasir** [comment]
> @frknasir Did you have any solution/patch in mind to make this package available for tenant base application.

I have been using 'akaunting/settings' package...it's multi tenant friendly

**Comment by rubenvanassche** [comment]
Hi @atapatel and @frknasir,

This package can actually be used with multi-tenancy, it was build for a project that uses the `spatie/multitenancy` package. The only thing required is adding a new `SettingsProperty` class:

```php
use Spatie\LaravelSettings\Models\SettingsProperty as BaseSettingsProperty;
use Spatie\Multitenancy\Models\Concerns\UsesTenantConnection;

class SettingsProperty extends BaseSettingsProperty
{
    use UsesTenantConnection;
}
```

And updating the database repository in `settings.php`:

```php
'database' => [
    'type' => Spatie\LaravelSettings\SettingsRepositories\DatabaseSettingsRepository::class,
    'model' => \App\Support\Settings\SettingsProperty::class,
    'connection' => null,
],
```

**Comment by atapatel** [comment]
@rubenvanassche Thanks for the solutions. although, I have found alternate solutions to use it with tenant approach.

**Comment by jouniikaheimo** [comment]
I have same multitenant issue package archtechx/tenancy... any tips how that solve?

**Comment by Atiladanvi** [comment]
@jouniikaheimo  If you have a signle databse just add a tenant collun to migration and make your custom model and config it here:
```php
 'database' => [
    'type' => Spatie\LaravelSettings\SettingsRepositories\DatabaseSettingsRepository::class,
    'model' => \App\Support\Settings\SettingsProperty::class,
    'connection' => null,
],
```

**Comment by jouniikaheimo** [comment]
@Atiladanvi  No i have multi database i try to about one hour before that. but not working

**Comment by Atiladanvi** [comment]
@jouniikaheimo  Try move the migration to tenant folder. The package auto recognize the connection is needed

**Comment by coding-sunshine** [comment]
@atapatel are you using https://github.com/archtechx/tenancy  ?
I am using ** https://github.com/archtechx/tenancy ** with single database tenancy and added added tenant_id column in the settings table and also tried to override the repository but doesn't work :(

**Comment by coding-sunshine** [comment]
Hi @atapatel @Atiladanvi any help would be appreciated please

**Comment by Atiladanvi** [comment]
> Hi @atapatel and @frknasir,
> 
> This package can actually be used with multi-tenancy, it was build for a project that uses the `spatie/multitenancy` package. The only thing required is adding a new `SettingsProperty` class:
> 
> ```
> use Spatie\LaravelSettings\Models\SettingsProperty as BaseSettingsProperty;
> use Spatie\Multitenancy\Models\Concerns\UsesTenantConnection;
> 
> class SettingsProperty extends BaseSettingsProperty
> {
>     use UsesTenantConnection;
> }
> ```
> 
> And updating the database repository in `settings.php`:
> 
> ```
> 'database' => [
>     'type' => Spatie\LaravelSettings\SettingsRepositories\DatabaseSettingsRepository::class,
>     'model' => \App\Support\Settings\SettingsProperty::class,
>     'connection' => null,
> ],
> ```

@coding-sunshine Would that work for you?

```php
use Spatie\LaravelSettings\Models\SettingsProperty as BaseSettingsProperty;
use Stancl\Tenancy\Database\Concerns\BelongsToTenant;


class SettingsProperty extends BaseSettingsProperty
{
    use BelongsToTenant;
}

**Comment by coding-sunshine** [comment]
Great! Thanks @Atiladanvi

**Comment by Atiladanvi** [comment]
@coding-sunshine Nice. Keep all clean. Wonderful.

**Comment by ricventu** [comment]
For per user settings you can try this:
https://github.com/ricventu/Laraconfig

**Comment by yllndritb** [comment]
For me, this from the discussion worked:
https://github.com/spatie/laravel-settings/discussions/39#discussioncomment-2687438
