### ISSUE TITLE
conflict with package Data-transfer-object

### ISSUE THREAD

**Issue by sawirricardo** [spatie/laravel-settings#65]
I hope this image is self-explanatory. Do you mind to have a look about this issue? Thank you.

<img width="1236" alt="Screen Shot 2021-04-25 at 15 26 51" src="https://user-images.githubusercontent.com/37329575/115986531-cfa3bc80-a5da-11eb-814d-85aeb99b2ea7.png">

**Comment by rubenvanassche** [comment]
This should be fixed with version: 2.1.4
