### ISSUE TITLE
Docblocks for properties not working

### ISSUE THREAD

**Issue by ricklambrechts** [spatie/laravel-settings#69]
Hi,

Most of the things are working great, thanks!

But when using the provided option inside a settings class:
```
/** @var int[]|null  */
public $an_array_of_ints_or_null;
```

I get the exception:
```
ArraySettingsCast::__construct(): Argument #1 ($cast) must be of type Spatie\LaravelSettings\SettingsCasts\SettingsCast, null given. (SettingsCastFactory.php on line 69)
```

**Comment by rubenvanassche** [comment]
Hi @ricklambrechts,

This should be fixed with v2.1.5!

**Comment by ricklambrechts** [comment]
Awesome!

**Comment by ricklambrechts** [comment]
@rubenvanassche Packagist is not showing the new version. Could you look in to it?

**Comment by rubenvanassche** [comment]
That's strange, updated it: https://packagist.org/packages/spatie/laravel-settings

**Comment by argonzalez2016** [comment]
This is not working when using the cache

**Comment by rubenvanassche** [comment]
Hi @argonzalez2016, could you provide me an example. Casts are only used to transform values between repository and settings class. When caching we serialize the complete setttings object so the values should be exactly the same as before caching.

**Comment by argonzalez2016** [comment]
I found the issue. I was trying to cache a laravel collection and it was calling the toArray method before serializing.

**Comment by rubenvanassche** [comment]
Yeah, personally, I wouldn't use too complex types within a settings class because that opens the door for a lot of things that can go wrong. But technically it is possible 😄
